//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int aId { get; set; }
        public string aName { get; set; }
        public string aType { get; set; }
        public string aAuthor { get; set; }
        public Nullable<System.DateTime> aReleaseTime { get; set; }
        public string aRemark { get; set; }
        public Nullable<int> aAmountOfAccess { get; set; }
        public Nullable<int> aCommentNum { get; set; }
        public Nullable<int> adId { get; set; }
    }
}
