//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKEntities : DbContext
    {
        public BKEntities()
            : base("name=BKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Album { get; set; }
        public DbSet<Answer> Answer { get; set; }
        public DbSet<Articles> Articles { get; set; }
        public DbSet<BlogPaperComments> BlogPaperComments { get; set; }
        public DbSet<BlogPaperReply> BlogPaperReply { get; set; }
        public DbSet<BlogPaperType> BlogPaperType { get; set; }
        public DbSet<ConsumptionType> ConsumptionType { get; set; }
        public DbSet<Head> Head { get; set; }
        public DbSet<ImageIndex> ImageIndex { get; set; }
        public DbSet<Integral> Integral { get; set; }
        public DbSet<IntegralRecord> IntegralRecord { get; set; }
        public DbSet<Problems> Problems { get; set; }
        public DbSet<Problems_Type> Problems_Type { get; set; }
        public DbSet<PublishBlogPaper> PublishBlogPaper { get; set; }
        public DbSet<UserDetail> UserDetail { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
