//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integral
    {
        public int Iid { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<int> oldTotal { get; set; }
        public Nullable<int> newTotal { get; set; }
        public Nullable<int> Consumption { get; set; }
    }
}
