//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegralRecord
    {
        public int IRid { get; set; }
        public Nullable<int> CTid { get; set; }
        public Nullable<int> Expenditure_id { get; set; }
        public Nullable<int> Income_id { get; set; }
        public Nullable<int> Transac { get; set; }
        public Nullable<System.DateTime> IRtime { get; set; }
    }
}
