//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problems
    {
        public int Problems_Id { get; set; }
        public Nullable<int> Problems_Type_Id { get; set; }
        public Nullable<int> Problems_UserId { get; set; }
        public Nullable<System.DateTime> Problems_Time { get; set; }
        public string Problems_Title { get; set; }
        public string Problems_Content { get; set; }
        public Nullable<int> Problems_SeeCount { get; set; }
        public Nullable<int> Problems_CollectCount { get; set; }
        public Nullable<int> Problems_IsSolve { get; set; }
        public Nullable<int> Problems_Money { get; set; }
        public Nullable<int> Problems_BestAnswerId { get; set; }
    }
}
