//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Detail_Id { get; set; }
        public string Detail_Name { get; set; }
        public Nullable<int> Detail_Sex { get; set; }
        public Nullable<System.DateTime> Detail_Birthday { get; set; }
        public string Detail_UserImg { get; set; }
        public string Detail_Position { get; set; }
        public string Detail_Region { get; set; }
        public string Detail_Region2 { get; set; }
        public string Detail_Region3 { get; set; }
        public string Detail_Industry { get; set; }
        public string Detail_SelfIntro { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
